#! /bin/sh
xsetroot -cursor_name left_ptr &
nitrogen --restore &
picom &
lxpolkit &
sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d      
# bspc monitor -d 1 2 3 4 5 6

bspc config border_width           1
bspc config window_gap            20

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Application settings
bspc -a chromium desktop='^4'
