#! /bin/sh
lxpolkit &
nitrogen --set-zoom-fill --random /home/b4uc/git/wallpapers/ &
sxhkd &
picom &
dunst &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI 

bspc config border_width           1
bspc config window_gap            20

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
